name: First workflow
on: push
jobs:
    first_job:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps: 
            - name: Welcome message
              run: echo "Welcome to GetHub actions."

            - name: Checkout repo step
              uses: actions/checkout@v6

            - name: List files and read README.md file
              run: |
                ls -l
                pwd
                cat README.md
            - name: Generate ASCII artwork
              run: |
                cowsay -f dragon "Run for cover, I am DRAGON..........." >> dragon.txt
                cat dragon.txt
                

           
  