name: Matrix workflow
on: push
jobs:
    deployment:
        strategy:
            matrix:
                os: [ubuntu-latest , windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Run hello-world on ${{ matrix.os }}
              run: docker run hello-world

      


