name: Matrix workflow
on: push
jobs:
    Linux-deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Docker details
              run: echo docker info
    Windows-deployment:
        runs-on: windows-latest
        steps:
            - name: Echo Docker details
              run: docker info


