name: Run ASCII workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout repo step
              uses: actions/checkout@v6
            
            - name: executing script
              run: |
                chmod +x run-ascii.sh
                sh run-ascii.sh
            - name: list files
              run: ls -la


           
  