name: Run ASCII workflow
on: push
jobs:
    Build_job_1:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout repo step
              uses: actions/checkout@v6
            
            - name: executing script
              run: |
                chmod +x run-ascii.sh
                sh run-ascii.sh
                # sleep 5
            - name: list files
              run: ls -la

            - name: Upload dragon.txt file
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file
                path: dragon.txt

    Deploy_job_2:
        needs: [Build_job_1]
        runs-on: ubuntu-latest
        
        steps: 
            - name: Checkout repo step
              uses: actions/checkout@v6
              
            - name: Download artiface
              uses: actions/download-artifact@v8
              with:
                name: dragon-text-file

            - name: List files
              run: ls -la

            - name: Check dragon availability
              run : |
                grep -i dragon dragon.txt

            - name: Print dragon
              run: cat dragon.txt
    


           
  