name: variables-secrets-workflow
on: 
  workflow_dispatch:
env:
    WORKFLOW: variables-secrets-workflow
concurrency:
  group: production-workflow
  cancel-in-progress: false
jobs:
    env-variables-job:
        runs-on: ubuntu-latest
        steps:
            - name: Assess step level env varaibles
              env:
                NAME: hanuman
              run: |
                echo "Accessing step level env variable - NAME: $NAME"
    
    job-env-variables:
        runs-on: ubuntu-latest
        env: 
          JOB: job-env-variables
          GOAL: make sure this env variable is accessable in all steps.
        steps:
            - name: first step
              run: |
                echo $JOB
                echo $GOAL
            - name: second step
              run: |
                echo $JOB
                echo $GOAL
    workflow-env-variables:
        runs-on: ubuntu-latest
        steps:
            - name: Accessing workflow level env variable
              run: |
                echo $WORKFLOW
                echo "Accessing secrets: ${{ secrets.PASSWORD }}"
                echo "Accessing repo variables: ${{ vars.USERNAME }}"