name: variables-secrets-workflow
on: push
jobs:
    env-variables-job:
        runs-on: ubuntu-latest
        steps:
            - name: Assess step level env varaibles
              env:
                NAME: hanuman
              run: |
                echo "Accessing step level env variable - NAME: $NAME"
    
    job-env-variables:
        runs-on: ubuntu-latest
        env: 
          JOB: job-env-variables
          GOAL: make sure this env variable is accessable in all steps.
        steps:
            - name: first step
              run: |
                echo $JOB
                echo $GOAL
            - name: second step
              run: |
                echo $JOB
                echo $GOAL
                