name: Workflow filters & Activities
on:
    push:
        branches:
            - main #Only trigger the workflow on main branch
            - '!feature/*' #Ignore branches name starts with "feature/"
    workflow_dispatch:
    pull_request:
        types:
            - opened
            - closed
        # paths-ignore:
        #     - README.md
        branches:
            - main
jobs:
    filters_job:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on various activites"
              run: "echo this workflow is running for the event type - ${{ github.event_name }}"